// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyACcCAMayMjFJF1iA-jc5o7B5a4vYiW2yk',
    appId: '1:551953685265:web:effcf2767108948abe8ab0',
    messagingSenderId: '551953685265',
    projectId: 'appmgk',
    authDomain: 'appmgk.firebaseapp.com',
    storageBucket: 'appmgk.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxogBlt6LAOOF_OMJwA10Vaz3ntB6LTRc',
    appId: '1:551953685265:android:103385c3fee9f35abe8ab0',
    messagingSenderId: '551953685265',
    projectId: 'appmgk',
    storageBucket: 'appmgk.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyACcCAMayMjFJF1iA-jc5o7B5a4vYiW2yk',
    appId: '1:551953685265:web:c1fe38aaa2d30a41be8ab0',
    messagingSenderId: '551953685265',
    projectId: 'appmgk',
    authDomain: 'appmgk.firebaseapp.com',
    storageBucket: 'appmgk.firebasestorage.app',
  );
}
